/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmsSlugRouteImport } from './routes/algorithms/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsSlugRoute = AlgorithmsSlugRouteImport.update({
  id: '/algorithms/$slug',
  path: '/algorithms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/algorithms/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/algorithms/$slug'
  id: '__root__' | '/' | '/algorithms/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmsSlugRoute: typeof AlgorithmsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$slug': {
      id: '/algorithms/$slug'
      path: '/algorithms/$slug'
      fullPath: '/algorithms/$slug'
      preLoaderRoute: typeof AlgorithmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmsSlugRoute: AlgorithmsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
